import Head from 'next/head'
import react from 'react'
import Image from 'next/image'
import Navbar from '@/components/Navbar'
import Hero from '@/components/Home'


export default function Home() {
  return (
    <>
      <Head>
        <title>Aly | Front-end Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/logo.png" />
      </Head>
      <Navbar/>
      <Hero/>
    </>
  )
}
