import Head from 'next/head'



export default function Home() {
  return (
    <>
      <Head>
        <title>Aly's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/logo.png" />
      </Head>
      <main>
        <section className="bg-white min-h-screen ">
        <nav>
          <h1
        </nav>
        </section>
      </main>
    </>
  )
}
