import Head from 'next/head'
import react from 'react'
import Image from 'next/image'
import Navbar from '@/components/Navbar'
import Hero from '@/components/Main'
import About from '@/components/About'
import Skills from '@/components/Skills/Skills'
import Back from '@/components/Background/Back'
import Projects from '@/components/Projects'
import Contact from '@/components/Contact'



export default function Home() {
  return (
    <>
      <Head>
        <title>Aly | Front-end Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/logo.png" />
      </Head>
      <Back/>
      <Navbar/>
      <Hero/>
      <About/>
      <Skills/>
      <Projects/>
      <Contact/>
    </>
  )
}
